apiVersion: apps/v1
kind: Deployment
metadata:
  name: &service-name http-server-docker-kubernetes-project
  labels: &labels
    app: *service-name
spec:
  minReadySeconds: 1
  selector:
    matchLabels: *labels
  replicas: 1
  revisionHistoryLimit: 10
  template: 
    metadata:
      labels: *labels
    spec:
      containers:
      - name: *service-name
        image: suda2001/http-server-docker-kubernetes-project:v1
        resources:
          limits:
          memory: 512Mi
          cpu: "1"
      requests:
        memory: 256Mi
        cpu: "0.2"
        command: ["./binary"]