apiVersion: v1
kind: Service
metadata:
  name: &service-name http-server-docker-kubernetes-project
spec:
  type: NodePort
  selector:
    app: *service-name
  ports:
    - name: http
      port: 10000
      nodePort: 30900 # I am assingning nodePort 30900 because nodePort has to be in range 30000-32767
      protocol: TCP